route:
    group_by: [Alertname]
    group_interval: 30s
    repeat_interval: 30s
    # Send all notifications to me.
    receiver: email-me
receivers:
- name: email-me
  email_configs:
  - send_resolved: true
    to: rkolupula589@gmail.com
    from: rkolupula589@gmail.com
    smarthost: smtpout.secureserver.net:587
    auth_username: "rkolupula589@gmail.com"
    auth_identity: "rkolupula589@gmail.com"
    auth_password: "Callbooking123"
    tls_config:
          insecure_skip_verify: true
